#!/bin/bash
set -euo pipefail #bash strict mode
[ "$#" -eq 0 ] && echo USAGE: "$0 files_to_remove_embedded_art_from..." && echo && echo "IMPLEMENTATION:" && cat "$0" && echo && exit 22 #usage message for invalid number of arguments
#removes embedded album art
#and is bit exact
for i in "$@" ; do
  ffmpeg -i "$i" -acodec copy -fflags +bitexact -vn tmp.artless."$i"
  mv tmp.artless."$i" "$i"
done
