#!/bin/bash

# this script tells git you are me
# or, if arguments are supplied,
# you are someone else.

if [ "$#" -ne 0 ] && [ "$#" -ne 2 ]; then
  echo "Usage: be-wyatt [user.name user.email]" >&2
  exit 1
fi

name=${1:-wyattscarpenter}
email=${2:-wyattscarpenter@gmail.com}

git config user.name "$name"
git config user.email "$email"