#!/bin/bash

echo Trimming trailing whitespace...
echo Note: this script DELIBERATELY treats CRLF line endings as erroneous, and corrects them to LF line endings. This should be fine for almost every application nowadays.

# Thanks to https://stackoverflow.com/questions/149057/how-to-remove-trailing-whitespace-of-all-files-recursively#comment78251151_149081, which I modified.
# [^\S\n] is \s but without \n (the actual newline). Thanks to https://stackoverflow.com/questions/3469080/match-whitespace-but-not-newlines/3469155#3469155 for this.
find . -not \( -name .svn -prune -o -name .git -prune \) -type f -print0 | xargs -0 -P 16 perl -pi -e 's/[^\S\n]+$//'

echo Enforcing the existence of exactly a single trailing newline...
echo "This program is very slow, because it reads all the files into memory, even though it just has to read the last bytes and see if there are any \ns there. Well, that said, I'm tired of writing the program now, so whatever..."

# Thanks to https://stackoverflow.com/questions/39540837/require-exactly-1-trailing-newline-in-a-file/39540892#39540892 for this general idea.
find . -not \( -name .svn -prune -o -name .git -prune \) -type f -print0 | xargs -0 -P 16 perl -i -0777 -wpe 's/\n*$/\n/'
