#!/bin/sh

# adapted from https://docs.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 filepath (as specified from the git root directory, I think)" >&2
  exit 1
fi

git filter-branch --force --index-filter "git rm -r --cached --ignore-unmatch \"$1\"" --prune-empty --tag-name-filter cat -- --all
