#!/bin/bash
# this script called by the populate-mmusic-dir command
# takes two arguments:
# 1: the file we are transfering from
# 2: the file we are transfering to (will end with the same extension as 1)
if ! ([[ -f "$2" ]] || [[ -f "$2.m4a" ]])
then
    d=`dirname "$2"`
    [[ -d "$d" ]] || mkdir -p "$d"
    if [ "${1: -4}" = ".mp3" ] || [ "${1: -4}" = ".m4a" ]
    then
	cp -n "$1" "$2" && echo "$2"
    else
	ffmpeg -loglevel error -n -i "$1" -vn "$2.m4a" && echo "$2.m4a"
    fi
fi

