#!/bin/bash
set -euo pipefail #bash strict mode
[ "$#" -eq 0 ] && echo USAGE: "$0 arguments..." && echo && echo "IMPLEMENTATION:" && cat "$0" && echo && exit 22 #usage message for invalid number of arguments

for i in "$@"
do
  mkdir -p tmp-ocr-"$i"
  cp "$i" tmp-ocr-"$i"
  cd tmp-ocr-"$i"
  split-pdf-into-images "$i"
  tessall *.png
  cp tess.txt ../"$1".ocr.txt
  cd ..
  rm -r tmp-ocr-"$i"
done
