#!/bin/bash
#recontainers using ffmpeg, and also excludes video streams
set -euo pipefail #bash "strict mode"
[ "$#" -lt 2 ] && echo USAGE: "$0 new_file_extention filenames..." && echo && echo "IMPLEMENTATION:" && cat "$0" && echo && exit 22 #usage message for invalid number of arguments

extension="$1"
shift
for i in "$@"; do
  ffmpeg -loglevel warning -fflags +bitexact -i "$i" -vn -c copy "$i.$extension"
done
