#!/bin/bash
set -euo pipefail #bash strict mode
[ "$#" -eq 0 ] && echo USAGE: "$0 image_files_left_to_right..." && echo && echo "IMPLEMENTATION:" && cat "$0" && echo && exit 22 #usage message for invalid number of arguments

#automatically find biggest height
max_height=0
for file in "$@"
do
  file_height=$(identify -format "%[h]" "$file")
  max_height=$(( $max_height > $file_height ? $max_height : $file_height ))
done

echo convert "$@" -resize "x$max_height" +append "$max_height"x.out.png
convert "$@" -resize "x$max_height" +append "$max_height"x.out.png
