#!/bin/bash
set -euo pipefail #bash strict mode
[ "$#" -eq 0 ] && echo USAGE: "$0 image_files_up_to_down..." && echo && echo "IMPLEMENTATION:" && cat "$0" && echo && exit 22 #usage message for invalid number of arguments

#automatically find widest width
max_width=0
for file in "$@"
do
  file_width=$(identify -format "%[w]" "$file")
  max_width=$(( $max_width > $file_width ? $max_width : $file_width ))
done

echo convert "$@" -resize "$max_width" -append "$max_width"x.out.png
convert "$@" -resize "$max_width" -append "$max_width"x.out.png
