#!/bin/sh
[ "$#" -eq 0 ] && echo USAGE: "$0 arguments..." && echo && echo "IMPLEMENTATION:" && cat "$0" && echo && exit 22 #usage message for invalid number of arguments

# This is a command where you pass in a command (as a string that may have spaces in it) and further arguments and then run the command on the further arguments, one at a time, retrying until it works.
# It is purposefully non-parallel, to allow for cases where that would be bad (thrashing, DDOSing, etc)
# I mostly got this to work, but in my actual use-case, Bash quoting is so cursed that it's somehow sending an EOF to SSL somewhere down the pipe...!

# Largely generated by ChatGPT, although eventually I had to edit it for taste and functionality:

command="$1"
shift

for arg do # Did you know this iterates the command-line arguments, respecting spaces? Me neither, until today.
    echo "\n\n" $command "$arg" "\n\n" >&2
    until $command "$arg"; do
        echo "\n\nCOMMAND '$command' FAILED for '$arg'. Retrying in 1 second...\n\n" >&2
        sleep 1
    done
done
