#!/usr/bin/env python3
# Generated by ChatGPT, with human guidance and touch-ups

import argparse
import shlex
import subprocess
import time


def main():
    parser = argparse.ArgumentParser(
        description="Retry a command for each argument until it succeeds." +
        + "Please excuse this vague documentation, which was in places written by a robot."
        + "See the implementation file for more details."
        + "\n\nAlso, have you considered just using GNU parallel?"
    )
    parser.add_argument(
        "command",
        help="Command to run (e.g. 'scp user@host:/dest')."
        + "Mind the quoting here. It's not that you have to quote for the benefit of this program,"
        + "but rather for the benefit of your shell which is inputting arguments to the program"
        + "and might (as shells are wont to do) like to split up arguments on spaces, etc."
    )
    parser.add_argument(
        "args",
        nargs="*",
        help="Arguments to append to the command, one at a time.",
    )
    ns = parser.parse_args()

    command = shlex.split(ns.command)

    for arg in ns.args:
        while subprocess.run([*command, arg]).returncode != 0:
            print(f"Command failed for {arg!r}. Retrying in 1 second...")
            time.sleep(1)


if __name__ == "__main__":
    main()