#!/bin/bash
#a bash script to make the flac gooder
#removes embedded album art
#and is bit exact
for i in *.flac ; do
    ffmpeg -i "$i" -acodec copy -fflags +bitexact -vn -map_metadata -1 "$(basename "${i/.flac}")..flac"
done
for i in *.mp3 ; do
    ffmpeg -i "$i" -acodec copy -fflags +bitexact -vn -map_metadata -1 "$(basename "${i/.mp3}")..mp3"
done
for i in *.m4a ; do
    ffmpeg -i "$i" -acodec copy -fflags +bitexact -vn -map_metadata -1 "$(basename "${i/.m4a}")..m4a"
done
for i in *.wav ; do
    ffmpeg -i "$i" -acodec copy -fflags +bitexact -vn -map_metadata -1 "$(basename "${i/.wav}")..wav"
done
rename -f "s/\.\././" *