#!/bin/bash
set -euo pipefail #bash strict mode
[ "$#" -eq 0 ] && echo USAGE: "$0 arguments..." && echo && echo "IMPLEMENTATION:" && cat "$0" && echo && exit 22 #usage message for invalid number of arguments

for i in "$@"
do
  echo "$i"
  tesseract "$i" stdout --psm 1 --dpi 150 >>tess.txt
done
