#!/bin/bash
set -euo pipefail #bash strict mode
[ "$#" -eq 0 ] && echo USAGE: "$0 commands_to_print_the_text_of..." && echo && echo "IMPLEMENTATION:" && cat "$0" && echo && exit 22 #usage message for invalid number of arguments
for i in "$@" ; do
  target=`whereis $i | cut -d ':' -f 2 | sed -e 's/^[[:space:]]*//'` #this removes lreading whitespace
  if [ -z "$target" ] ; then
    echo "$i not found by whereis" 1>&2
  else
    cat "$target"
  fi
done
