#!/bin/bash
# Thanks to https://stackoverflow.com/questions/149057/how-to-remove-trailing-whitespace-of-all-files-recursively#comment78251151_149081, which I modified.
# [^\S\n] is \s but without \n (the actual newline). Thanks to https://stackoverflow.com/questions/3469080/match-whitespace-but-not-newlines/3469155#3469155 for this.
# This script DELIBERATELY treats CRLF line endings as erroneous, and corrects them to LF line endings. This should be fine for almost every application nowadays.
find . -not \( -name .svn -prune -o -name .git -prune \) -type f -print0 | xargs -0 perl -pi -e 's/[^\S\n]+$//'
