#!/bin/bash
set -uo pipefail #bash strict mode, except -e because we need short-circuiting for the slick || && below
[ "$#" -eq 0 ] && echo USAGE: "$0 arguments..." && echo && echo "IMPLEMENTATION:" && cat "$0" && echo && exit 22 #usage message for invalid number of argument
# We just forward to aptitude; you may also use the flag --show-summary to show only the final requiring package (although in my limited experience this often omits the package that is the reason, due to said package only "recommending" the installed package). We forward all the arguments but unforunately it seems like only the last one is honored by aptitude why. --show-summary does not break the aptitude show grep bit, either.
(aptitude --version >/dev/null 2>/dev/null) || (echo "Installing aptitude to answer the question, please wait..." ; apt-fast install -y aptitude >/dev/null 2>/dev/null) && (aptitude why "$@") && (aptitude show "$@" | grep 'Automatically installed')
