#!/bin/bash
set -euo pipefail #bash strict mode
[ "$#" -lt 2 ] || [ "$#" -gt 3 ] && echo USAGE: "$0 target-url starting-timestamp [ending-timestamp]" && echo && echo "IMPLEMENTATION:" && cat "$0" && echo && exit 22 #usage message for invalid number of arguments

b="$(basename $1)"
if [ $# -eq 3 ]; then
  optional_to_param="-to ${3@Q}"
else
  optional_to_param=""
fi
# The cut command here is only needed because yt-dlp -g returns two urls, which are separated by a newline. I don't really know why, nor what that means, nor if it always happens, or what. I pick the first one arbitrarily. #edit: this seems to be video and then audio
ffmpeg -ss "$2" -i $(yt-dlp -g "$1" | cut -d $'\n' -f1) $optional_to_param -c copy -copyts "${b##*=}.youtube-dl-part.mp4"
