#!/bin/bash
# calls youtube-upload-url in parallel on any number of command line arguments (urls)
# unclear how one might specify any options to youtube-upload-url here
echo "$@" | xargs -P 0 -n 1 youtube-upload-url
